#!/usr/bin/env python3
"""
huffman_codec.py — Word-Level Huffman Codec for LoRa Mesh Messages
===================================================================
v7.0: Dual codebook support (4K legacy + 333K from Kaggle dataset).

The 333K codebook loads pre-built codes from codebooks/huffman_333k.bin
(generated by build_huffman_codebook_333k.py). The 4K codebook builds
the Huffman tree at init time from huffman_codebook_4k.csv (legacy).

v7.0 additions:
  - codebook_size parameter: '4k' or '333k'
  - encode_keywords(): tightly packed bits across keyword boundaries
  - decode_keywords(): decode N keywords from contiguous bitstream
  - ESC fallback preserved for both codebook sizes

Key features (unchanged from v4):
  - Spaces between words are IMPLICIT (no space bit needed for word→word)
  - Case bits: 0=lowercase (1 bit), 10=Capitalized, 11=UPPER (2 bit)
  - "No-space" flag is the rare case (only before punctuation), 1-bit penalty
  - Numbers after NUM token use tighter encoding
  - ESC fallback for out-of-codebook words

Author: Mark Snow, Jr. — CyberMesh / Liberty Mesh Project
Date:   March 2026
"""

import csv
import heapq
import logging
import os
import pickle
import re
import time
from dataclasses import dataclass, field
from typing import Optional

logger = logging.getLogger(__name__)


@dataclass(order=True)
class HuffmanNode:
    freq: int
    char: Optional[str] = field(default=None, compare=False)
    left: Optional["HuffmanNode"] = field(default=None, compare=False)
    right: Optional["HuffmanNode"] = field(default=None, compare=False)


def build_huffman_tree(freq_table: dict[str, int]) -> HuffmanNode:
    heap = [HuffmanNode(freq=f, char=w) for w, f in freq_table.items()]
    heapq.heapify(heap)
    while len(heap) > 1:
        lo = heapq.heappop(heap)
        hi = heapq.heappop(heap)
        heapq.heappush(heap, HuffmanNode(freq=lo.freq + hi.freq, left=lo, right=hi))
    return heap[0]


def build_codebook(root: HuffmanNode) -> dict[str, str]:
    codes: dict[str, str] = {}
    def walk(node, prefix=""):
        if node.char is not None:
            codes[node.char] = prefix or "0"
            return
        if node.left:  walk(node.left,  prefix + "0")
        if node.right: walk(node.right, prefix + "1")
    walk(root)
    return codes


# Control tokens — artificial entries in the Huffman tree
_ESC  = "\x00ESC"
_NUM  = "\x00NUM"
_PUNCT = "\x00PUN"
_NOSPACE = "\x00NSP"  # "next token has NO space before it"
_EOF     = "\x00EOF"  # end of stream marker


class MeshHuffmanCodec:
    """
    Static word-level Huffman codec for LoRa mesh messages.

    v7.0: Supports '4k' and '333k' codebook sizes.

    For '4k': Builds Huffman tree at init from huffman_codebook_4k.csv.
              Full encode/decode with case bits, numbers, punctuation, ESC.
    For '333k': Loads pre-built codes from codebooks/huffman_333k.bin.
                Full encode/decode plus keyword-specific methods.

    Encoding philosophy:
      - Spaces between tokens are IMPLICIT (most common case)
      - When a token should NOT have a preceding space, emit _NOSPACE first
      - Case: 1-bit flag after word code. 0=lowercase, 1=prefix for cap/upper
      - Numbers: _NUM + var-length binary
      - Unknown words: _ESC + 5-bit length + 7-bit ASCII chars
      - Punctuation: _PUNCT + 7-bit ASCII
    """

    def __init__(self, codebook_csv_path: Optional[str] = None,
                 codebook_size: str = "4k"):
        """
        Args:
            codebook_csv_path: Explicit CSV path (overrides codebook_size auto-detect).
            codebook_size: '4k' or '333k'. Default '4k' for backward compat.
        """
        self.codebook_size = codebook_size
        self.codebook_source = "unknown"

        base = os.path.dirname(os.path.abspath(__file__))

        if codebook_size == "333k" and codebook_csv_path is None:
            self._init_333k(base)
        else:
            self._init_4k(base, codebook_csv_path)

        self._tok_re = re.compile(
            r"([a-zA-Z]+(?:'[a-zA-Z]+)?)"
            r"|([0-9]+(?:\.[0-9]+)?)"
            r"|(\s+)"
            r"|([^\s])"
        )

    def _init_333k(self, base: str):
        """Load pre-built 333K codebook from .bin file."""
        bin_path = os.path.join(base, "codebooks", "huffman_333k.bin")
        if not os.path.exists(bin_path):
            raise FileNotFoundError(
                f"333K codebook not found: {bin_path}\n"
                "Run build_huffman_codebook_333k.py first.")

        t0 = time.perf_counter()
        with open(bin_path, "rb") as f:
            data = pickle.load(f)
        load_ms = (time.perf_counter() - t0) * 1000

        self._333k_word_to_code: dict[str, str] = data["word_to_code"]
        self._333k_code_to_word: dict[str, str] = data["code_to_word"]
        self.codebook_source = "huffman_333k"

        # Build the full encode/decode tables for text mode:
        # Start with all 333K word codes
        self.encode_table: dict[str, str] = dict(self._333k_word_to_code)

        # Add control tokens — assign codes that don't collide with word codes
        # Use the same frequency-based approach as 4K but with 333K scale
        # We need short codes for controls, so we rebuild a small combined tree
        # Actually, for 333K mode we need control tokens too.
        # Approach: use dedicated prefix codes that cannot appear in the Huffman tree.
        # Since the 333K tree already uses all prefix-free codes, we use a simple
        # escape mechanism: a reserved word acts as the ESC marker.
        # For v7.0, keywords don't need control tokens (they're just word codes).
        # Full text mode still needs them — so we rebuild the tree with controls added.
        self._build_333k_text_tables()

        logger.info("Huffman 333K loaded: %d words in %.0f ms",
                     len(self._333k_word_to_code), load_ms)

    def _build_333k_text_tables(self):
        """
        Build encode/decode tables for full text mode with 333K codebook.

        For text encoding (not keyword mode), we need control tokens (ESC, NUM,
        PUNCT, NOSPACE, EOF) alongside the word codes. We rebuild a Huffman tree
        from the 333K frequencies plus control tokens.

        This is expensive (~2s) but only runs once at init.
        """
        base = os.path.dirname(os.path.abspath(__file__))
        freq_path = os.path.join(base, "english_unigram_freq.csv")

        if os.path.exists(freq_path):
            # Load frequencies to rebuild tree with controls
            freq: dict[str, int] = {}
            with open(freq_path, "r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    word = row["word"].strip().lower()
                    try:
                        count = int(row["count"])
                    except (ValueError, TypeError):
                        continue
                    if count > 0 and word:
                        freq[word] = count

            # Add control tokens
            word_freqs = sorted(freq.values(), reverse=True)
            mid = word_freqs[len(word_freqs) // 2] if word_freqs else 1_000_000
            freq[_NOSPACE] = mid * 3
            freq[_NUM]     = mid * 2
            freq[_PUNCT]   = mid * 2
            freq[_ESC]     = mid
            freq[_EOF]     = 1

            t0 = time.perf_counter()
            tree = build_huffman_tree(freq)
            self.encode_table = build_codebook(tree)
            self.decode_table = {v: k for k, v in self.encode_table.items()}
            build_ms = (time.perf_counter() - t0) * 1000
            logger.info("Huffman 333K text tree built in %.0f ms", build_ms)
        else:
            # Fallback: use 333K codes for words, synthesize control codes
            # This is a degraded mode — text encode/decode may not work correctly
            # but keyword encode/decode will work fine.
            logger.warning("Frequency file not found for 333K text mode: %s",
                           freq_path)
            self.encode_table = dict(self._333k_word_to_code)
            self.decode_table = {v: k for k, v in self.encode_table.items()}

    def _init_4k(self, base: str, codebook_csv_path: Optional[str]):
        """Load 4K codebook (legacy path, unchanged from v4)."""
        if codebook_csv_path is None:
            path_4k = os.path.join(base, "huffman_codebook_4k.csv")
            path_legacy = os.path.join(base, "english_unigram_freq.csv")
            if os.path.exists(path_4k):
                codebook_csv_path = path_4k
                self.codebook_source = "huffman_codebook_4k"
            else:
                codebook_csv_path = path_legacy
                self.codebook_source = "english_unigram_freq_legacy"

        self.freq_table = self._build_freq_table_4k(codebook_csv_path)
        tree = build_huffman_tree(self.freq_table)
        self.encode_table = build_codebook(tree)
        self.decode_table = {v: k for k, v in self.encode_table.items()}

    def _build_freq_table_4k(self, csv_path: str) -> dict[str, int]:
        """
        Build frequency table from 4K codebook CSV.

        Supports two formats:
          - huffman_codebook_4k.csv: columns word, huffman_code, bits, frequency
          - english_unigram_freq.csv: columns word, count (legacy fallback)
        """
        freq: dict[str, int] = {}
        if not os.path.exists(csv_path):
            raise FileNotFoundError(f"Codebook not found: {csv_path}")

        with open(csv_path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            fields = reader.fieldnames or []

            if "huffman_code" in fields:
                # 4K format: word, huffman_code, bits, frequency
                for row in reader:
                    w = row["word"].strip().lower()
                    if w == "<esc>":
                        continue
                    try:
                        c = int(row["frequency"])
                    except ValueError:
                        continue
                    freq[w] = c
            else:
                # Legacy format: word, count
                loaded = 0
                for row in reader:
                    vals = list(row.values())
                    if len(vals) < 2:
                        continue
                    w = vals[0].strip().lower()
                    try:
                        c = int(vals[1])
                    except ValueError:
                        continue
                    if len(w) == 1 and w not in {"a", "i"}:
                        continue
                    if w.isdigit():
                        continue
                    freq[w] = c
                    loaded += 1
                    if loaded >= 4000:
                        break
                # Legacy: also merge domain words
                for w, c in MESH_DOMAIN_WORDS_LEGACY.items():
                    freq[w.lower()] = max(freq.get(w.lower(), 0), c)
                sorted_w = sorted(freq.items(), key=lambda x: x[1], reverse=True)
                freq = dict(sorted_w[:2048])

        # Add control tokens with appropriate frequencies
        word_freqs = sorted(freq.values(), reverse=True)
        mid = word_freqs[len(word_freqs) // 2] if word_freqs else 1_000_000
        freq[_NOSPACE] = mid * 3
        freq[_NUM]     = mid * 2
        freq[_PUNCT]   = mid * 2
        freq[_ESC]     = mid
        freq[_EOF]     = 1  # rare = long code, but we only emit it once

        return freq

    def _tokenize(self, text: str) -> list[tuple[str, str, bool]]:
        """Returns (type, value, space_before) triples."""
        tokens = []
        space_pending = False
        for m in self._tok_re.finditer(text):
            word, number, ws, punct = m.groups()
            if ws is not None:
                space_pending = True
                continue
            if word:     tokens.append(("word", word, space_pending))
            elif number: tokens.append(("number", number, space_pending))
            elif punct:  tokens.append(("punct", punct, space_pending))
            space_pending = False
        return tokens

    # ---- sub-encoders (unchanged from v4) ----

    @staticmethod
    def _encode_number(n: int) -> str:
        if n < 0:
            return "1" + MeshHuffmanCodec._encode_number(-n)[1:]  # flip sign
        if n <= 255:
            return "0" + "00" + format(n, "08b")       # 11 bits
        elif n <= 65535:
            return "0" + "01" + format(n, "016b")       # 19 bits
        else:
            return "0" + "10" + format(n & 0xFFFFFFFF, "032b")  # 35 bits

    @staticmethod
    def _decode_number(bits: str, pos: int) -> tuple[int, int]:
        neg = bits[pos] == "1"; pos += 1
        lc = bits[pos:pos+2]; pos += 2
        widths = {"00": 8, "01": 16, "10": 32}
        w = widths.get(lc)
        if w is None: raise ValueError(f"Bad num len: {lc}")
        v = int(bits[pos:pos+w], 2); pos += w
        return (-v if neg else v), pos

    @staticmethod
    def _encode_raw(word: str) -> str:
        w = word[:31]
        return format(len(w), "05b") + "".join(format(ord(c) & 0x7F, "07b") for c in w)

    @staticmethod
    def _decode_raw(bits: str, pos: int) -> tuple[str, int]:
        n = int(bits[pos:pos+5], 2); pos += 5
        chars = []
        for _ in range(n):
            chars.append(chr(int(bits[pos:pos+7], 2))); pos += 7
        return "".join(chars), pos

    @staticmethod
    def _encode_case(word: str) -> str:
        """0 = lowercase (1 bit), 10 = Capitalized (2 bits), 11 = UPPER (2 bits)"""
        if word.islower():
            return "0"
        if len(word) > 1 and word[0].isupper() and word[1:].islower():
            return "10"
        if word.isupper():
            return "11"
        return "10"  # fallback: treat as capitalized

    @staticmethod
    def _apply_case(word: str, bits: str, pos: int) -> tuple[str, int]:
        if bits[pos] == "0":
            return word.lower(), pos + 1
        pos += 1
        if bits[pos] == "0":
            return word.capitalize(), pos + 1
        else:
            return word.upper(), pos + 1

    # ---- encode (full text — unchanged from v4) ----

    def encode(self, text: str) -> bytes:
        """
        Encode text. Default assumption: space between every pair of tokens.
        When a token should NOT have a space, emit _NOSPACE before it.
        First token never has a space.

        Returns: encoded bytes (payload only, no header).
        """
        tokens = self._tokenize(text)
        bits = ""
        first = True

        for tok_type, tok_val, space_before in tokens:
            if not first:
                # Default is "space before". If no space, emit NOSPACE marker.
                if not space_before:
                    bits += self.encode_table[_NOSPACE]

            first = False

            if tok_type == "word":
                wl = tok_val.lower()
                if wl in self.encode_table:
                    bits += self.encode_table[wl]
                    bits += self._encode_case(tok_val)
                else:
                    bits += self.encode_table[_ESC]
                    bits += self._encode_raw(tok_val)

            elif tok_type == "number":
                if '.' in tok_val:
                    bits += self.encode_table[_ESC]
                    bits += self._encode_raw(tok_val)
                else:
                    bits += self.encode_table[_NUM]
                    bits += self._encode_number(int(tok_val))

            elif tok_type == "punct":
                bits += self.encode_table[_PUNCT]
                bits += format(ord(tok_val) & 0x7F, "07b")

        # End-of-stream: emit EOF Huffman code
        bits += self.encode_table[_EOF]
        r = len(bits) % 8
        if r: bits += "0" * (8 - r)
        return int(bits, 2).to_bytes(len(bits) // 8, byteorder="big")

    # ---- decode (full text — unchanged from v4) ----

    def decode(self, data: bytes) -> str:
        bits = bin(int.from_bytes(data, byteorder="big"))[2:].zfill(len(data) * 8)
        pos = 0
        result = []
        first = True
        nospace_next = False

        while pos < len(bits):
            # Decode next Huffman code
            code = ""
            decoded = None
            while pos < len(bits):
                code += bits[pos]; pos += 1
                if code in self.decode_table:
                    decoded = self.decode_table[code]
                    break
            if decoded is None:
                break

            # Handle control tokens
            if decoded == _EOF:
                break
            if decoded == _NOSPACE:
                nospace_next = True
                continue

            # Insert space before this token (unless first or nospace)
            if not first and not nospace_next:
                result.append(" ")
            nospace_next = False
            first = False

            if decoded == _ESC:
                w, pos = self._decode_raw(bits, pos)
                result.append(w)
            elif decoded == _NUM:
                v, pos = self._decode_number(bits, pos)
                result.append(str(v))
            elif decoded == _PUNCT:
                ch = chr(int(bits[pos:pos+7], 2)); pos += 7
                result.append(ch)
            else:
                # Regular word + case
                w, pos = self._apply_case(decoded, bits, pos)
                result.append(w)

        return "".join(result)

    # ---- keyword encode/decode (NEW v7.0) ----

    def encode_keywords(self, keywords: list[str]) -> bytes:
        """
        Encode a list of keywords into tightly packed bytes.

        CRITICAL: Bits are packed contiguously across keyword boundaries.
        A 12-bit code followed by a 15-bit code = 27 contiguous bits (4 bytes),
        NOT 2 + 2 bytes. The keyword count in the packet header tells the
        decoder how many codes to read.

        Keywords are lowercase (pretokenizer already ran). No case bits,
        no space markers, no EOF — just raw Huffman codes concatenated.
        Unknown words use ESC + raw encoding.

        Args:
            keywords: List of lowercase keyword strings.

        Returns:
            Encoded bytes (tightly packed, padded to byte boundary).
        """
        t0 = time.perf_counter()
        bits = ""
        esc_count = 0

        # Use the appropriate lookup table
        if self.codebook_size == "333k":
            lookup = self._333k_word_to_code
        else:
            lookup = {k: v for k, v in self.encode_table.items()
                      if not k.startswith("\x00")}

        for kw in keywords:
            kw_lower = kw.lower().strip()
            if kw_lower in lookup:
                bits += lookup[kw_lower]
            else:
                # ESC fallback: encode as raw ASCII
                # Use a marker that the decoder can recognize
                if _ESC in self.encode_table:
                    bits += self.encode_table[_ESC]
                    bits += self._encode_raw(kw_lower)
                else:
                    # No ESC token available — use raw encoding with length prefix
                    raw = kw_lower.encode("utf-8")
                    bits += format(len(raw), "08b")
                    for b in raw:
                        bits += format(b, "08b")
                esc_count += 1
                logger.debug("Huffman keyword ESC: '%s'", kw_lower)

        if esc_count > 0:
            logger.info("Huffman encode_keywords: %d/%d ESC sequences",
                         esc_count, len(keywords))

        # Pad to byte boundary
        r = len(bits) % 8
        if r:
            bits += "0" * (8 - r)

        elapsed_ms = (time.perf_counter() - t0) * 1000

        if not bits:
            return b""
        return int(bits, 2).to_bytes(len(bits) // 8, byteorder="big")

    def decode_keywords(self, payload: bytes, count: int) -> list[str]:
        """
        Decode exactly 'count' keywords from tightly packed payload bytes.

        Reads Huffman codes sequentially from the bitstream until 'count'
        keywords have been decoded. Uses the same ESC handling as encode.

        Args:
            payload: Encoded bytes (tightly packed).
            count: Number of keywords to decode.

        Returns:
            List of decoded keyword strings.
        """
        t0 = time.perf_counter()

        if not payload or count <= 0:
            return []

        bits = bin(int.from_bytes(payload, byteorder="big"))[2:].zfill(
            len(payload) * 8)

        # Build decode table for keywords
        if self.codebook_size == "333k":
            kw_decode = self._333k_code_to_word
        else:
            kw_decode = {v: k for k, v in self.encode_table.items()
                         if not k.startswith("\x00")}

        # We also need to recognize the ESC code for fallback words
        esc_code = self.encode_table.get(_ESC)

        keywords = []
        pos = 0

        while len(keywords) < count and pos < len(bits):
            code = ""
            decoded = None

            while pos < len(bits):
                code += bits[pos]
                pos += 1

                # Check for ESC
                if esc_code and code == esc_code:
                    decoded = _ESC
                    break

                # Check for word
                if code in kw_decode:
                    decoded = kw_decode[code]
                    break

            if decoded is None:
                logger.warning("Huffman decode_keywords: premature end at "
                               "keyword %d/%d", len(keywords), count)
                break

            if decoded == _ESC:
                # Read raw word
                w, pos = self._decode_raw(bits, pos)
                keywords.append(w)
            else:
                keywords.append(decoded)

        elapsed_ms = (time.perf_counter() - t0) * 1000
        logger.debug("Huffman decode_keywords: %d keywords in %.1f ms",
                      len(keywords), elapsed_ms)
        return keywords

    # ---- analysis ----

    def stats(self) -> dict:
        cl = [len(v) for k, v in self.encode_table.items() if not k.startswith("\x00")]
        ctrl = {t: len(self.encode_table.get(t, "")) for t in [_ESC, _NUM, _PUNCT, _NOSPACE, _EOF]}
        return {
            "codebook_size": len(self.encode_table) - 5,
            "codebook_source": self.codebook_source,
            "codebook_size_config": self.codebook_size,
            "min_bits": min(cl), "max_bits": max(cl),
            "avg_bits": sum(cl) / len(cl),
            "controls": ctrl,
        }

    def analyze(self, text: str) -> dict:
        raw = len(text.encode("utf-8"))
        comp = self.encode(text)
        cb = len(comp)
        dec = self.decode(comp)
        return {
            "original": text, "decoded": dec,
            "raw_bytes": raw, "comp_bytes": cb,
            "ratio": raw / cb if cb else float("inf"),
            "savings_pct": (1 - cb / raw) * 100 if raw else 0,
            "roundtrip": dec == text,
            "headroom": 230 - cb,
        }

    def codebook_coverage(self, text: str) -> dict:
        toks = self._tokenize(text)
        words = [t[1] for t in toks if t[0] == "word"]
        inc = sum(1 for w in words if w.lower() in self.encode_table)
        return {
            "total": len(words), "in_cb": inc,
            "coverage": inc / len(words) * 100 if words else 100,
            "missing": [w for w in words if w.lower() not in self.encode_table],
        }


# Legacy domain words — only used if falling back to english_unigram_freq.csv
MESH_DOMAIN_WORDS_LEGACY = {
    "node": 50_000_000, "mesh": 50_000_000, "sensor": 45_000_000,
    "packet": 45_000_000, "signal": 40_000_000, "radio": 40_000_000,
    "frequency": 35_000_000, "antenna": 35_000_000, "channel": 35_000_000,
    "gateway": 30_000_000, "repeater": 30_000_000, "lora": 30_000_000,
    "rssi": 25_000_000, "snr": 25_000_000, "gps": 25_000_000,
    "latitude": 20_000_000, "longitude": 20_000_000, "altitude": 20_000_000,
    "battery": 25_000_000, "voltage": 20_000_000, "solar": 20_000_000,
    "firmware": 20_000_000, "reboot": 18_000_000, "uptime": 18_000_000,
    "hop": 20_000_000, "hops": 20_000_000, "route": 20_000_000,
    "neighbor": 18_000_000, "neighbors": 18_000_000, "topology": 15_000_000,
    "broadcast": 18_000_000, "ping": 18_000_000, "ack": 18_000_000,
    "timeout": 15_000_000, "retry": 15_000_000, "queue": 15_000_000,
    "payload": 15_000_000, "header": 15_000_000, "checksum": 15_000_000,
    "sos": 50_000_000, "emergency": 40_000_000, "dispatch": 35_000_000,
    "flood": 18_000_000, "storm": 18_000_000, "alert": 25_000_000,
    "humidity": 15_000_000, "temperature": 20_000_000,
}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    import sys
    size = "4k"
    if "--333k" in sys.argv:
        size = "333k"

    codec = MeshHuffmanCodec(codebook_size=size)
    s = codec.stats()

    print("=" * 78)
    print(f"  HUFFMAN CODEC v7.0 — CyberMesh / Liberty Mesh")
    print(f"  Codebook: {s['codebook_size_config']} ({s['codebook_size']:,} words from {s['codebook_source']})")
    print("=" * 78)
    print(f"  Codes:     {s['min_bits']}–{s['max_bits']} bits (avg {s['avg_bits']:.1f})")
    ctrl = s['controls']
    print(f"  Controls:  ESC={ctrl[_ESC]}b  NUM={ctrl[_NUM]}b  "
          f"PUNCT={ctrl[_PUNCT]}b  NOSPACE={ctrl[_NOSPACE]}b")

    msgs = [
        "ok",
        "SOS",
        "Battery at 89 percent",
        "Node 12 temperature 72 humidity 45",
        "The sensor node is reporting temperature 94 degrees",
        "Alert flood warning for the area",
        "What time is it?",
        "the sensor is online battery at 89 percent signal strong",
    ]

    print(f"\n{'=' * 78}")
    print(f"  COMPRESSION BENCHMARKS — 8 Test Messages (full text mode)")
    print(f"{'=' * 78}")
    hdr = f"  {'#':<3} {'Raw':>4} {'Cmp':>4} {'Ratio':>6} {'Sav%':>5} {'Head':>5} {'RT'} Message"
    print(hdr)
    print(f"  {'-'*3} {'-'*4} {'-'*4} {'-'*6} {'-'*5} {'-'*5} {'-'*2} {'-'*50}")

    tr = tc = 0
    ok = True
    for i, m in enumerate(msgs, 1):
        r = codec.analyze(m)
        tr += r["raw_bytes"]; tc += r["comp_bytes"]
        rt = "✓" if r["roundtrip"] else "✗"
        if not r["roundtrip"]: ok = False
        dm = m if len(m) <= 55 else m[:52] + "..."
        print(f"  {i:<3} {r['raw_bytes']:>4} {r['comp_bytes']:>4} "
              f"{r['ratio']:>6.2f} {r['savings_pct']:>4.0f}% {r['headroom']:>5} "
              f"{rt}  {dm}")
        if not r["roundtrip"]:
            print(f"      FAIL: '{r['decoded']}'")

    ar = tr / tc if tc else 0
    ap = (1 - tc / tr) * 100 if tr else 0
    am = tc / len(msgs)

    print(f"\n  {'─' * 76}")
    print(f"  AGGREGATE  {tr:>4} {tc:>4} {ar:>6.2f} {ap:>4.0f}%")
    print(f"  Avg compressed:  {am:.0f} bytes  |  Avg headroom: {230 - am:.0f} bytes")
    print(f"  Roundtrip:       {'100% PASS ✓' if ok else 'FAILURES ✗'}")

    # Keyword mode test
    print(f"\n{'=' * 78}")
    print(f"  KEYWORD MODE BENCHMARKS")
    print(f"{'=' * 78}")
    kw_tests = [
        ["flood", "warning", "active", "lawrence", "township", "sensors",
         "operational", "offline"],
        ["sensor", "5", "reads", "2", "feet", "rising"],
        ["emergency", "dispatch", "north", "sector", "3", "casualties"],
        ["battery", "89", "percent", "signal", "strong", "node", "12",
         "online"],
    ]
    kw_ok = True
    for i, kws in enumerate(kw_tests, 1):
        encoded = codec.encode_keywords(kws)
        decoded = codec.decode_keywords(encoded, len(kws))
        rt = decoded == kws
        if not rt:
            kw_ok = False
        print(f"  [{i}] {len(kws)} keywords → {len(encoded)} bytes "
              f"({len(encoded)*8} bits, "
              f"avg {len(encoded)*8/len(kws):.1f} bits/kw) "
              f"{'✓' if rt else '✗'}")
        if not rt:
            print(f"      IN:  {kws}")
            print(f"      OUT: {decoded}")

    print(f"\n  Keyword roundtrip: {'100% PASS ✓' if kw_ok else 'FAILURES ✗'}")
    print(f"{'=' * 78}")


if __name__ == "__main__":
    main()
