#!/usr/bin/env python3
"""
mux_codec.py — MUX Grid Codec for LoRa Mesh Messages (Experiment B)
=====================================================================
Word → index lookup into a 4,096-entry frequency-sorted codebook with
tiered variable-width bit packing.

Tier 0: Index   0-63   → prefix 0  + 6-bit index =  7 bits
Tier 1: Index  64-255  → prefix 10 + 8-bit index = 10 bits
Tier 2: Index 256-4095 → prefix 11 + 12-bit index = 14 bits

Index 4095 = ESC: emits 14-bit ESC marker + 8-bit length + raw UTF-8 bytes.

Packet format:
  Byte 0:    Codec ID (0x02 = MUX Grid)
  Byte 1:    Message sequence number (0-255)
  Byte 2:    Padding bits count (0-7)
  Bytes 3-N: Encoded payload (tiered bit-packed indices)

Author: Mark Snow, Jr. — Mindtech / CyberMesh / Liberty Mesh
Date:   March 2026
"""

import csv
import os
from typing import Optional

# Codec IDs for the unified packet header
CODEC_ID_HUFFMAN = 0x01
CODEC_ID_MUX_GRID = 0x02

# ESC index
ESC_INDEX = 4095


class MuxGridCodec:
    """
    MUX Grid codec: word → index → tiered bit packing.

    The codebook is loaded from mux_codebook.csv (generated by
    build_mux_codebook.py). Both nodes must hold identical copies.
    """

    def __init__(self, codebook_csv_path: Optional[str] = None):
        if codebook_csv_path is None:
            codebook_csv_path = os.path.join(
                os.path.dirname(os.path.abspath(__file__)),
                "mux_codebook.csv",
            )
        self.word_to_index: dict[str, int] = {}
        self.index_to_word: dict[int, str] = {}
        self.codebook_size = 0
        self._load_codebook(codebook_csv_path)

    def _load_codebook(self, path: str):
        """Load codebook from CSV."""
        if not os.path.exists(path):
            raise FileNotFoundError(f"Codebook not found: {path}")

        with open(path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                idx = int(row["index"])
                word = row["word"]
                if word == "<ESC>":
                    continue  # ESC is a reserved index, not a word
                self.word_to_index[word.lower()] = idx
                self.index_to_word[idx] = word.lower()

        self.codebook_size = len(self.word_to_index)

    # ── Bit-level encoding ──

    @staticmethod
    def _encode_index(idx: int) -> str:
        """Encode a single index using tiered bit packing."""
        if idx < 64:
            return "0" + format(idx, "06b")       # 7 bits
        elif idx < 256:
            return "10" + format(idx, "08b")       # 10 bits
        else:
            return "11" + format(idx, "012b")      # 14 bits

    @staticmethod
    def _encode_esc_word(word: str) -> str:
        """Encode an out-of-codebook word: ESC index + length + raw UTF-8."""
        raw = word.encode("utf-8")
        bits = MuxGridCodec._encode_index(ESC_INDEX)  # 14 bits
        bits += format(len(raw), "08b")                # 8-bit length
        for byte in raw:
            bits += format(byte, "08b")                # raw bytes
        return bits

    # ── Encode ──

    def encode(self, text: str) -> tuple[bytes, int]:
        """
        Encode text to compressed bytes.

        Returns:
            (payload_bytes, padding_bits) — raw payload without header.
            Use encode_packet() to get the full packet with 3-byte header.
        """
        words = text.lower().split()
        bitstream = ""

        for word in words:
            if word in self.word_to_index:
                idx = self.word_to_index[word]
                bitstream += self._encode_index(idx)
            else:
                bitstream += self._encode_esc_word(word)

        # Pad to byte boundary
        padding = (8 - len(bitstream) % 8) % 8
        bitstream += "0" * padding

        # Convert to bytes
        payload = int(bitstream, 2).to_bytes(len(bitstream) // 8, byteorder="big") if bitstream else b""
        return payload, padding

    def encode_packet(self, text: str, seq: int = 0) -> bytes:
        """
        Encode text to a full packet with 3-byte header.

        Byte 0: Codec ID (0x02)
        Byte 1: Sequence number
        Byte 2: Padding bits
        Bytes 3+: Encoded payload
        """
        payload, padding = self.encode(text)
        header = bytes([CODEC_ID_MUX_GRID, seq & 0xFF, padding & 0x07])
        return header + payload

    # ── Decode ──

    def decode(self, payload: bytes, padding_bits: int) -> str:
        """
        Decode raw payload bytes (without header) back to text.

        Args:
            payload: The encoded payload bytes.
            padding_bits: Number of trailing padding bits to trim.
        """
        if not payload:
            return ""

        # Convert to bitstream
        bitstream = bin(int.from_bytes(payload, byteorder="big"))[2:]
        bitstream = bitstream.zfill(len(payload) * 8)

        # Trim padding
        if padding_bits > 0:
            bitstream = bitstream[:-padding_bits]

        words = []
        pos = 0

        while pos < len(bitstream):
            remaining = len(bitstream) - pos
            if remaining < 7:
                break  # Not enough bits for even a Tier 0 code

            # Read prefix to determine tier
            if bitstream[pos] == "0":
                # Tier 0: 1-bit prefix + 6-bit index = 7 bits
                if remaining < 7:
                    break
                idx = int(bitstream[pos + 1:pos + 7], 2)
                pos += 7
            elif pos + 1 < len(bitstream) and bitstream[pos + 1] == "0":
                # Tier 1: 2-bit prefix "10" + 8-bit index = 10 bits
                if remaining < 10:
                    break
                idx = int(bitstream[pos + 2:pos + 10], 2)
                pos += 10
            else:
                # Tier 2: 2-bit prefix "11" + 12-bit index = 14 bits
                if remaining < 14:
                    break
                idx = int(bitstream[pos + 2:pos + 14], 2)
                pos += 14

            if idx == ESC_INDEX:
                # ESC: read 8-bit length + raw UTF-8 bytes
                if pos + 8 > len(bitstream):
                    break
                length = int(bitstream[pos:pos + 8], 2)
                pos += 8
                raw_bytes = bytearray()
                for _ in range(length):
                    if pos + 8 > len(bitstream):
                        break
                    raw_bytes.append(int(bitstream[pos:pos + 8], 2))
                    pos += 8
                words.append(raw_bytes.decode("utf-8"))
            elif idx in self.index_to_word:
                words.append(self.index_to_word[idx])
            else:
                words.append(f"<UNK:{idx}>")

        return " ".join(words)

    def decode_packet(self, packet: bytes) -> tuple[str, int, int, int]:
        """
        Decode a full packet with 3-byte header.

        Returns:
            (decoded_text, codec_id, seq, padding_bits)
        """
        if len(packet) < 3:
            raise ValueError(f"Packet too short: {len(packet)} bytes (need >= 3)")

        codec_id = packet[0]
        seq = packet[1]
        padding = packet[2]
        payload = packet[3:]

        text = self.decode(payload, padding)
        return text, codec_id, seq, padding

    # ── Analysis ──

    def analyze(self, text: str) -> dict:
        """Analyze compression for a single message."""
        raw_bytes = len(text.encode("utf-8"))
        packet = self.encode_packet(text)
        comp_bytes = len(packet)
        decoded, _, _, _ = self.decode_packet(packet)
        ratio = raw_bytes / comp_bytes if comp_bytes else float("inf")

        return {
            "original": text,
            "decoded": decoded,
            "raw_bytes": raw_bytes,
            "comp_bytes": comp_bytes,
            "header_bytes": 3,
            "payload_bytes": comp_bytes - 3,
            "ratio": ratio,
            "savings_pct": (1 - comp_bytes / raw_bytes) * 100 if raw_bytes else 0,
            "roundtrip": decoded == text.lower(),  # MUX lowercases everything
        }

    def stats(self) -> dict:
        """Codebook statistics."""
        return {
            "codebook_size": self.codebook_size,
            "tier_0_words": sum(1 for idx in self.word_to_index.values() if idx < 64),
            "tier_1_words": sum(1 for idx in self.word_to_index.values() if 64 <= idx < 256),
            "tier_2_words": sum(1 for idx in self.word_to_index.values() if 256 <= idx < 4095),
            "tier_0_bits": 7,
            "tier_1_bits": 10,
            "tier_2_bits": 14,
        }

    def codebook_coverage(self, text: str) -> dict:
        """Check how many words in the text are in the codebook."""
        words = text.lower().split()
        in_cb = sum(1 for w in words if w in self.word_to_index)
        missing = [w for w in words if w not in self.word_to_index]
        return {
            "total": len(words),
            "in_cb": in_cb,
            "coverage": in_cb / len(words) * 100 if words else 100,
            "missing": missing,
        }


# ---------------------------------------------------------------------------
# CLI — standalone test
# ---------------------------------------------------------------------------
def main():
    codec = MuxGridCodec()
    s = codec.stats()

    print("=" * 78)
    print("  MUX GRID CODEC — CyberMesh / Liberty Mesh — Experiment B")
    print("  4K codebook + tiered bit packing (7/10/14 bits)")
    print("=" * 78)
    print(f"  Codebook:  {s['codebook_size']} words")
    print(f"  Tier 0:    {s['tier_0_words']} words (indices 0-63, {s['tier_0_bits']} bits)")
    print(f"  Tier 1:    {s['tier_1_words']} words (indices 64-255, {s['tier_1_bits']} bits)")
    print(f"  Tier 2:    {s['tier_2_words']} words (indices 256-4095, {s['tier_2_bits']} bits)")

    # Test messages (identical to Experiment A)
    msgs = [
        "ok",
        "SOS",
        "Battery at 89 percent",
        "Node 12 temperature 72 humidity 45",
        "The sensor node is reporting temperature 94 degrees",
        "Alert flood warning for the area",
        "What time is it?",
        "the sensor is online battery at 89 percent signal strong",
    ]

    print(f"\n{'=' * 78}")
    print(f"  COMPRESSION BENCHMARKS — 8 Test Messages")
    print(f"{'=' * 78}")
    hdr = f"  {'#':<3} {'Raw':>4} {'Cmp':>4} {'Hdr':>3} {'Pay':>3} {'Ratio':>6} {'Sav%':>5} {'RT'} Message"
    print(hdr)
    print(f"  {'-'*3} {'-'*4} {'-'*4} {'-'*3} {'-'*3} {'-'*6} {'-'*5} {'-'*2} {'-'*50}")

    tr = tc = 0
    ok = True
    for i, m in enumerate(msgs, 1):
        r = codec.analyze(m)
        tr += r["raw_bytes"]
        tc += r["comp_bytes"]
        rt = "✓" if r["roundtrip"] else "✗"
        if not r["roundtrip"]:
            ok = False
        dm = m if len(m) <= 55 else m[:52] + "..."
        print(f"  {i:<3} {r['raw_bytes']:>4} {r['comp_bytes']:>4} "
              f"{r['header_bytes']:>3} {r['payload_bytes']:>3} "
              f"{r['ratio']:>6.2f} {r['savings_pct']:>4.0f}% "
              f"{rt}  {dm}")
        if not r["roundtrip"]:
            print(f"      ORIG: '{r['original']}'")
            print(f"      DECD: '{r['decoded']}'")

    ar = tr / tc if tc else 0
    ap = (1 - tc / tr) * 100 if tr else 0
    print(f"\n  {'─' * 76}")
    print(f"  AGGREGATE  {tr:>4} {tc:>4}              {ar:>6.2f} {ap:>4.0f}%")
    print(f"  Roundtrip: {'100% PASS ✓' if ok else 'FAILURES ✗'}")
    print(f"{'=' * 78}")


if __name__ == "__main__":
    main()
